include::header.adoc[]


=== Before We Get Started

You will need a system which has an RDP client in order to interact with the lab.

== Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not.  The format of this discussion is a combination of presentation, demonstration, and hands-on labs.

== Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 4 hours.
* Participate. We are going to cut you loose with Ansible here in just a little while. Have questions. Have opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!


== Conventions Used in This Document

[TIP]
Whenever you see a section like this, please pay close attention.  We are leading you through a process.




*Step 1:* Run this command to do something or other

[source,bash]
----
ansible windows -m setup
----

*Step 2:* Edit this file in this specific way

[source,bash]
----
---
- hosts: web
  name: This is a play within a playbook
  become: yes
  vars:
    httpd_packages:
      - httpd
      - mod_wsgi
----

[IMPORTANT]
Do not cut and paste text from this document.  We really want you to learn ansible during this workshop,
and part of that experience is typing out YAML and understanding its syntax, spacing, and alignments.

== Document Copyright

This document was created by and for Red Hat, Inc. It is being released under link:https://creativecommons.org/licenses/by/4.0/[Creative Commons License 4.0]. You are free to re-use it in whole or in part.

You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

include::setup.adoc[]

