---
- name: Provision Instances
  hosts: localhost
  gather_facts: False
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - manage-instances
  vars:
    teardown: false
  tasks:
  - include_role:
      name: "check_setup"
  - include_role:
      name: "manage-{{ instance_loc }}-instances"

- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows-ad-controller
  roles:
    - windows-ad-controller

- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows_hosts
  roles:
    - windows-common

- name: Configure GitLab Host
  hosts: gitlab
  become: True
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - gitlab
  roles:
    - { role: linux-common }
    - { role: geerlingguy.gitlab }

# Run post-config separate to avoid handler restart issue...
- name: Gitlab Post Config
  hosts: gitlab
  become: True
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - gitlab
  roles:
    - { role: gitlab-postconfig }

- name: Configure Ansible Host
  hosts: tower
  become: True
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - ansible-tower
  roles:
    - linux-common
    - ansible-tower

- name: Configure Windows Workstation
  hosts: windows_workstations
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - windows-workstation
  roles:
    - windows-common
    - windows-workstation

- name: Configure Docs Host
  hosts: docs
  become: True
  gather_facts: True
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - docs
  roles:
    - linux-common
    - docs_nginx
    - docs_setup

- name: Display Login Information
  hosts: localhost
  gather_facts: False
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tags:
    - docs-info
  tasks:
    - name: Login Information
      debug:
        msg:
          - Student Login  - http://{{ hostvars['docs'].ansible_host }}/users/
          - Lab Slide Deck - http://{{ hostvars['docs'].ansible_host }}/decks/
    - name: Build workshop information
      template:
        src: "{{ playbook_dir }}/templates/workshop.txt.j2"
        dest: "{{ playbook_dir }}/workshops/{{ name_prefix }}/workshop.txt"
