---
- name: find ami id for rhel 7
  ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel7'] }}"
      architecture: x86_64
    region: "{{ ec2_region }}"
  register: rhel7_ami_find

- name: find ami id for rhel 8
  ec2_ami_info:
    owners: 309956199498
    filters:
      name: "{{ ec2_image_names['rhel8'] }}"
      architecture: x86_64
    region: "{{ ec2_region }}"
  register: rhel8_ami_find

- name: find ami id for centos 7
  ec2_ami_info:
    owners: aws-marketplace
    filters:
      name: "{{ ec2_image_names['centos7'] }}"
      architecture: x86_64
    region: "{{ ec2_region }}"
  register: centos7_ami_find

- name: find ami for windows 2016 core
  ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2016_core'] }}"
    region: "{{ ec2_region }}"
  register: win2016_core_ami_find

- name: find ami for windows 2016 full
  ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2016_full'] }}"
    region: "{{ ec2_region }}"
  register: win2016_full_ami_find

- name: find ami for windows 2019 core
  ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2019_core'] }}"
    region: "{{ ec2_region }}"
  register: win2019_core_ami_find

- name: find ami for windows 2019 full
  ec2_ami_info:
    filters:
      name: "{{ ec2_image_names['win2019_full'] }}"
    region: "{{ ec2_region }}"
  register: win2019_full_ami_find

- name: set ami ids
  set_fact:
    ec2_ami_ids:
      rhel7: "{{ rhel7_ami_find.images[-1].image_id | default('') }}"
      rhel8: "{{ rhel8_ami_find.images[-1].image_id | default('') }}"
      centos7: "{{ centos7_ami_find.images[-1].image_id | default('') }}"
      win2016_core: "{{ win2016_core_ami_find.images[-1].image_id | default('') }}"
      win2016_full: "{{ win2016_full_ami_find.images[-1].image_id | default('') }}"
      win2019_core: "{{ win2019_core_ami_find.images[-1].image_id | default('') }}"
      win2019_full: "{{ win2019_full_ami_find.images[-1].image_id | default('') }}"

- debug:
    var: ec2_ami_ids
  when:
    - ec2_ami_ids is defined

- name: fail if one/more of the selected EC2 AMIs not found
  fail:
    msg: |
      One of the specified EC2 AMIs not found:

      {% if ec2_ami_ids[ec2_tower_instance_ami_type] == '' %}
      ec2_tower_instance_ami_type is set to "{{ ec2_tower_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
      {% if ec2_ami_ids[ec2_gitlab_instance_ami_type] == '' %}
      ec2_gitlab_instance_ami_type is set to "{{ ec2_gitlab_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
      {% if ec2_ami_ids[ec2_docs_instance_ami_type] == '' %}
      ec2_docs_instance_ami_type is set to "{{ ec2_docs_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
      {% if ec2_ami_ids[ec2_windc_instance_ami_type] == '' %}
      ec2_windc_instance_ami_type is set to "{{ ec2_windc_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
      {% if ec2_ami_ids[ec2_windows_workstation_instance_ami_type] == '' %}
      ec2_windows_workstation_instance_ami_type is set to "{{ ec2_windows_workstation_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
      {% if ec2_ami_ids[ec2_windows_instance_ami_type] == '' %}
      ec2_windows_instance_ami_type is set to "{{ ec2_windows_instance_ami_type }}" but not found, see the debug output above.
      {% endif %}
  when: >
    ec2_ami_ids[ec2_tower_instance_ami_type] == '' or
    ec2_ami_ids[ec2_gitlab_instance_ami_type] == '' or
    ec2_ami_ids[ec2_docs_instance_ami_type] == '' or
    ec2_ami_ids[ec2_windc_instance_ami_type] == '' or
    ec2_ami_ids[ec2_windows_workstation_instance_ami_type] == '' or
    ec2_ami_ids[ec2_windows_instance_ami_type] == ''